i18n:
  ui:
    pressStart:
      en: "Press to start"
      de: "Start mit Knopfdruck"
    decisionMade:
      en: 'A decision has been made…'
      de: 'Eine Entscheidung wurde getroffen…'
    waitingToBegin:
      en: 'Get ready! A new game will begin soon.'
      de: 'Mach dich bereit! Ein neues Spiel beginnt bald.'
    waitingToEnd:
      en: 'Waiting for the other players…'
      de: 'Warte auf die anderen Spieler*innen…'
    pressToContinue:
      en: 'Press to continue'
      de: 'Weiter mit Knopfdruck'
    defaultPrompt:
     en: "You are at a math conference and meet different mathematicians. Do they produce research data? Try to find out!"
     de: "Du bist auf einer Mathe-Konferenz und triffst verschiedene Mathematiker*innen. Produzieren sie Forschungsdaten? Versuche, das herauszufinden!"

    
    includedInDecision:
      en: 'Included in the decision'
      de: 'In die Entscheidung einbezogen'
    inclusionBarTitle:
      en: 'Who decides?'
      de: 'Wer entscheidet?'
