players:
  # <id>: // A unique id (integer) for the player
  #   color: '#rrggbb' //  the color that identifies the player
  #   spawn: { x: number, y: number } The spawn point of the player
  #   enabled: true // Whether the player is enabled or not (defaults to true)
  1:
    color: '#27a6a8'
    spawn: { x: 2741, y: 3232 }
  2:
    color: '#d331a3'
    spawn: { x: 2841, y: 3232 }
  3:
    color: '#ea7a24'
    spawn: { x: 2941, y: 3232 }
