textures:
  bundles:
    - name: 'town-view'
      assets:
        - name: 'town-bg'
          srcs: 'https://futurium-democracy-tmp.s3.eu-central-1.amazonaws.com/demo-town-bg.png'
        - name: 'town-collmap'
          srcs: 'demo-town-collmap.png'
        - name: 'character-basic'
          srcs: 'character-basic.json'
        - name: 'npcs-demo'
          srcs: 'npcs-demo.json'
        - name: 'mood-balloon'
          srcs: 'mood-balloon.json'
        - name: 'map-markers'
          srcs: 'map-markers.json'
        - name: 'icons'
          srcs: 'icons.json'
