textures:
  bundles:
    - name: 'town-view'
      assets:
        - name: 'town-bg'
          srcs: 'demo-town-bg.png'
        - name: 'town-collmap'
          srcs: 'demo-town-collmap.png'
        - name: 'character-basic'
          srcs: 'character-basic.json'
        - name: 'npcs-demo'
          srcs: 'npcs-demo.json'
        - name: 'mood-balloon'
          srcs: 'mood-balloon.json'
        - name: 'mood-icons'
          srcs: 'mood-icons.json'
